name: Build Vulcan APK
on: [push]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Init Capacitor
        run: |
          npm install
          npx cap init "VulcanInject" "com.jordan.vulcan" --web-dir .
          npx cap add android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      # NEW STEP: Rename the output file before uploading
      - name: Rename Output
        run: mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/Vulcan_Mod_V1.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vulcan-Mod-Package
          path: android/app/build/outputs/apk/debug/Vulcan_Mod_V1.apk
